from enum import Enum

class TokenPatterns(Enum):
    COMMENT_LINE = r'\/\/.*'
    COMMENT_MULTI_START = r'\/\*.*?'
    COMMENT_MULTI_END = r'.*?(\*\/){1}?'
    IDENTIFIER = r'[a-zA-Z_]\w*\b'
    CONSTANT = r'[0-9]+\b'
    INCREMENT = r'\+\+'
    DECREMENT = r'--'
    PLUS = r'\+'
    MINUS = r'-'
    BITWISE_NOT = r'~'
    NOT = r'!'
    MULTIPLY = r'\*'
    DIVIDE = r'\/'
    AND = r'&&'
    OR = r'\|\|'
    EQ = r'=='
    NEQ = r'!='
    LTE = r'<='
    GTE = r'>='
    ASSIGN = r'='
    LT = r'<'
    GT = r'>'
    SEMICOLON = r';'
    LPAREN = r'\('
    RPAREN = r'\)'
    LBRACE = r'\{'
    RBRACE = r'\}'
    COMMA = r','
    KEYWORD = r'KEYWORD'
    ERROR = r'ERROR'
    EOF = r'EOF'