from enum import Enum

class TokenPatterns(Enum):
    COMMENT_LINE = r'\/\/.*'
    COMMENT_MULTI_START = r'\/\*.*?'
    COMMENT_MULTI_END = r'.*?(\*\/){1}?'
    IDENTIFIER = r'[a-zA-Z_]\w*\b'
    CONSTANT = r'[0-9]+\b'
    PLUS = r'\+'
    MINUS = r'-'
    MULTIPLY = r'\*'
    DIVIDE = r'\/'
    ASSIGN = r'='
    EQ = r'=='
    NEQ = r'!='
    LT = r'<'
    GT = r'>'
    LTE = r'<='
    GTE = r'>='
    SEMICOLON = r';'
    LPAREN = r'\('
    RPAREN = r'\)'
    LBRACE = r'\{'
    RBRACE = r'\}'
    COMMA = r','
    KEYWORD = r''
    ERROR = r''